###############################################################
# (!) CAUTION: DO NOT ALTER THIS FILE
###############################################################


version: '3.8'
services:
  backend:
    container_name: isk-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    
    
  frontend:
    depends_on:
      - backend
    container_name: isk-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443:443'
    

