###############################################################
# (!) CAUTION: DO NOT ALTER THIS FILE
###############################################################


version: '3.8'
services:
  backend:
    container_name: isk-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    
    
  frontend:
    depends_on:
      - backend
    container_name: isk-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile

    

