###############################################################
# (!) CAUTION: PLEASE DO NOT ALTER THIS FILE BY YOURSELF!
# IF WANT TO CHANGE ANYTHING THEN CONTACT TO THE ADMIN.
###############################################################


## Docker Services
version: '3.8'
services:

  ## Development Services ##
  dev-backend:
    container_name: isk-dev-backend
    environment:
      SENDER_EMAIL: $SENDER_EMAIL
      AUTH_TOKEN: $AUTH_TOKEN
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    profiles: [development]

  dev-frontend:
    depends_on:
      - dev-backend
    container_name: isk-dev-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    profiles: [development]
  ## Development Services ##

  ## Production Services ##
  prd-backend:
    container_name: isk-prd-backend
    environment:
      SENDER_EMAIL: $SENDER_EMAIL
      AUTH_TOKEN: $AUTH_TOKEN
    build:
      context: ./backend
      dockerfile: Dockerfile
    profiles: [production]
    
  prd-frontend:
    depends_on:
      - prd-backend
    container_name: isk-prd-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    profiles: [production]
  ## Production Services ##

